# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    with:
      working-directory: ./backend

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      working-directory: ./frontend

  terraform:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      working-directory: ./terraform
