# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  NODE_VERSION: '18'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    with:
      working-directory: ./backend
      node-version: ${{ env.NODE_VERSION }}

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      working-directory: ./frontend
      node-version: ${{ env.NODE_VERSION }}

  terraform:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      working-directory: ./terraform
