# .github/workflows/reusable_build.yml
name: Terraform workflows

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v3'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Terraform
        run: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform plan -var-file=dev.tfvars -out=tfplan
